name: Screenshot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           ref: main

      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://galerie-brutal.de/
          destination: screenshot.png
          width: 1200
          height: 900

      - uses: actions/download-artifact@v4
        with:
          name: screenshot

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update screenshot
          branch: main
          file_pattern: screenshot*.png
        
      - name: Clean
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: screenshot
